### ISSUE TITLE
Server crash on PlayerObject

### ISSUE THREAD

**Issue by alansyahdwi** [openmultiplayer/open.mp#1033]
My server crashes 3 times with the same gdb output.
OS: Debian 11
omp version: 1.3.1.2748

I've tried using [this omp version](https://github.com/openmultiplayer/open.mp/actions/runs/11611054690) but the crashes still occur with the same output.

```
Thread 1 "omp-server" received signal SIGSEGV, Segmentation fault.
PlayerObject::advance (this=0x302e3900, elapsed=..., now=...) at /code/Server/Components/Objects/object.cpp:241
241	/code/Server/Components/Objects/object.cpp: No such file or directory.
#0  PlayerObject::advance (this=0x302e3900, elapsed=..., now=...) at /code/Server/Components/Objects/object.cpp:241
#1  0xf4c68149 in ObjectComponent::onTick (this=0x8fafa00, elapsed=..., now=...) at /code/Server/Components/Objects/objects_main.cpp:26
#2  0xf4c68277 in non-virtual thunk to ObjectComponent::onTick(std::chrono::duration<long long, std::ratio<1ll, 1000000ll> >, std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> > >) () at /code/SDK/include/Impl/pool_impl.hpp:42
#3  0x08109e48 in Impl::DefaultEventDispatcher<CoreEventHandler>::dispatch<void, std::chrono::duration<long long, std::ratio<1ll, 1000000ll> >, std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> > >, std::chrono::duration<long long, std::ratio<1ll, 1000000ll> > const&, std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> > > const&> (this=<optimized out>, mf=&virtual CoreEventHandler::onTick(std::chrono::duration<long long, std::ratio<1ll, 1000000ll> >, std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> > >), args=..., args=...) at /code/SDK/include/Impl/events_impl.hpp:133
#4  Core::run (this=<optimized out>) at /code/Server/Source/core_impl.hpp:1418
#5  0x0810426b in main (argc=<optimized out>, argv=<optimized out>) at /code/Server/Source/server.cpp:153
```

**Comment by AmyrAhmady** [comment]
Can you try with latest version and confirm it's still happening? I'm closing this issue for now, you can reply with your results and I'll reopen it if it still exists
