### ISSUE TITLE
RakNet free memory crash

### ISSUE THREAD

**Issue by AmyrAhmady** [openmultiplayer/open.mp#739]
**Describe the bug**
A crash happens with call stack as below

**To Reproduce**
N/A

**Expected behavior**
Not to crash

**Screenshots and/or logs**
```
(gdb) bt
#0  0xf7fc4549 in __kernel_vsyscall ()
#1  0xf7cccaa7 in ?? () from /lib/i386-linux-gnu/libc.so.6
#2  0xf7c7b685 in raise () from /lib/i386-linux-gnu/libc.so.6
#3  0xf7c643ac in abort () from /lib/i386-linux-gnu/libc.so.6
#4  0xf7cbf3fc in ?? () from /lib/i386-linux-gnu/libc.so.6
#5  0xf7cd842f in ?? () from /lib/i386-linux-gnu/libc.so.6
#6  0xf7cda77c in ?? () from /lib/i386-linux-gnu/libc.so.6
#7  0xf7cdcc27 in free () from /lib/i386-linux-gnu/libc.so.6
#8  0x08329cd8 in operator delete(void*) ()
#9  0x08329288 in operator delete[](void*) ()
#10 0xf6a6a667 in RakNet::ReliabilityLayer::FreeThreadSafeMemory (this=0xe596ca6c) at /code/lib/RakNet/Source/ReliabilityLayer.cpp:302
#11 0xf6a6a094 in RakNet::ReliabilityLayer::FreeMemory (this=0xe596ca6c, freeAllImmediately=255) at /code/lib/RakNet/Source/ReliabilityLayer.cpp:112
#12 RakNet::ReliabilityLayer::Reset (this=0xe596ca6c, resetVariables=<optimized out>) at /code/lib/RakNet/Source/ReliabilityLayer.cpp:113
#13 0xf6a56ea2 in RakNet::RakPeer::CloseConnectionInternal (this=0x8d350a4, target=..., sendDisconnectionNotification=<optimized out>, performImmediate=<optimized out>, orderingChannel=0 '\000')
    at /code/lib/RakNet/Source/RakPeer.cpp:3518
#14 0xf6a5d6c5 in RakNet::RakPeer::RunUpdateCycle (this=<optimized out>) at /code/lib/RakNet/Source/RakPeer.cpp:4537
#15 0xf6a5449e in RakNet::UpdateNetworkLoop (arguments=0x8d350a4) at /code/lib/RakNet/Source/RakPeer.cpp:5063
#16 0xf7ccac01 in ?? () from /lib/i386-linux-gnu/libc.so.6
#17 0xf7d6775c in ?? () from /lib/i386-linux-gnu/libc.so.6
```

**Release version**
Works on RC and latest nightly

**Additional info**
In one occurrence it seems to be happening after a player is kicked/banned, there's no confirmation if it's actually related

**Comment by AmyrAhmady** [comment]
Fixed by removed pre join packet handlers and extra packet data validity check
